# Development environment overrides
database:
  memory: true
  max_connections: 1

analytics:
  dashboard:
    port: 5000
    host: "127.0.0.1"
  
  queries:
    breakout_patterns:
      max_results: 100  # Smaller for faster dev queries