# Global configuration for the trading platform
performance:
  fast_mode: false
  connection_pool_enabled: true
  connection_pool_size: 10
  connection_pool_timeout: 30.0
  skip_complex_verification: false
  verification_timeout: 5.0
  essential_checks_only: false
  query_cache_enabled: true
  query_cache_ttl: 300
  prepared_statements_enabled: true
  performance_monitoring: false
  metrics_collection: false

scanners:
  default:
    obv_threshold: 100.0
    volume_multiplier: 1.5
    breakout_period: 20
  strategies: {}
  backtest:
    max_iterations: 1000
    timeframe: "1d"

database:
  path: "data/financial_data.duckdb"
  memory: false
  extension_dir: "./extensions"
  max_connections: 5

brokers:
  default: "dhan"
  brokers:
    dhan:
      api_key: "dummy_key"
      api_secret: "dummy_secret"
      access_token: "dummy_token"
    tradehull:
      api_key: "dummy_key_th"
      api_secret: "dummy_secret_th"
      access_token: "dummy_token_th"
  endpoints:
    dhan: "https://api.dhan.co"
    tradehull: "https://api.tradehull.com"
  rate_limit: 100

analytics:
  queries:
    breakout_patterns:
      timeout: 30
      max_results: 1000
  rules: []
  dashboard:
    port: 8080
    host: "localhost"
  indicators:
    - rsi
    - macd
    - obv