# Database module configuration
path: "data/financial_data.duckdb"
memory: false
extension_dir: "./extensions"
max_connections: 5
schema:
  market_data:
    create_sql: |
      CREATE TABLE IF NOT EXISTS market_data (
          symbol VARCHAR NOT NULL,
          timestamp TIMESTAMP NOT NULL,
          open DECIMAL(10,2) NOT NULL,
          high DECIMAL(10,2) NOT NULL,
          low DECIMAL(10,2) NOT NULL,
          close DECIMAL(10,2) NOT NULL,
          volume BIGINT NOT NULL,
          timeframe VARCHAR NOT NULL,
          date_partition DATE NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (symbol, timestamp, timeframe)
      )
  symbols:
    create_sql: |
      CREATE TABLE IF NOT EXISTS symbols (
          symbol VARCHAR PRIMARY KEY,
          name VARCHAR,
          sector VARCHAR,
          industry VARCHAR,
          exchange VARCHAR DEFAULT 'NSE',
          first_date DATE,
          last_date DATE,
          total_records BIGINT DEFAULT 0,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
  scanner_results:
    create_sql: |
      CREATE TABLE IF NOT EXISTS scanner_results (
          id VARCHAR PRIMARY KEY,
          scanner_name VARCHAR NOT NULL,
          symbol VARCHAR NOT NULL,
          timestamp TIMESTAMP NOT NULL,
          signals JSON,
          execution_time_ms FLOAT,
          success BOOLEAN DEFAULT TRUE,
          error_message VARCHAR,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
  indexes:
    market_data_symbol_date: "CREATE INDEX IF NOT EXISTS idx_market_data_symbol_date ON market_data(symbol, date_partition)"
    market_data_timestamp: "CREATE INDEX IF NOT EXISTS idx_market_data_timestamp ON market_data(timestamp)"
    scanner_results_symbol: "CREATE INDEX IF NOT EXISTS idx_scanner_results_symbol ON scanner_results(symbol)"
    scanner_results_timestamp: "CREATE INDEX IF NOT EXISTS idx_scanner_results_timestamp ON scanner_results(timestamp)"