# Trade Engine Configuration - Single Source of Truth
# ====================================================

mode: backtest                    # backtest | live
trading_day: "2025-08-20"         # backtest date; ignored in live
universe: NIFTY500

# Trading Hours
time:
  warmup_start: "09:15"
  shortlist_cutoff: "09:50"
  eod_flat: "15:15"

# Data Configuration
data:
  duckdb_path: "data/financial_data.duckdb"
  bars:
    trigger_timeframe: "1m"
    risk_timeframe: "5m"
  live_ws: "wss://api.dhan.co/marketfeed"  # For live trading

# Symbol Selection Criteria
selection:
  turnover_min_crore: 5.0
  spread_bps_max: 15
  blacklist: []
  score_weights:
    ret_0915_0950: 0.35
    vspike_10m: 0.25
    obv_delta_35m: 0.20
    sector_strength: 0.10
    range_compression: 0.10
    spread_penalty: -0.20
    illiq_penalty: -0.20

# Entry Configuration
entry:
  triggers: ["ema_9_30", "range_break", "tape_confirm"]
  range_break:
    lookback_min: 15
    vol_mult: 1.3
  ema_9_30:
    body_top_pct: 40

# Risk Management
risk:
  per_trade_r_pct: 0.75
  k_atr_initial: 1.6
  dd_daily_stop_pct: 2.5
  sector_cap_pct: 60

# Position Sizing
sizing:
  capital_split: [0.6, 0.2, 0.2]   # A/B/C ranks
  slippage_bps: 5
  fee_bps: 2

# Pyramiding Rules
pyramiding:
  add_levels_r: [0.75, 1.25, 2.0]
  add_sizes_frac: [0.5, 0.33, 0.25]
  tsl:
    mode: chandelier_atr
    k_steps: [2.0, 1.7, 1.5]

# Rotation Logic
rotation:
  check_after_minutes: 20
  min_leader_r: 0.5

# Guardrails
limits:
  max_reentries_15m: 3
  max_adds: 3
  eod_flat_time: "15:15"

# Broker Configuration
broker:
  name: "dhan"
  tick_size_map: "trade_engine/config/nse_ticks.yaml"
  rounding: nearest_tick

# Telemetry
telemetry:
  log_level: "INFO"
  write_to_duckdb: true
  metrics:
    enable_pnl_tracking: true
    enable_order_tracking: true
    enable_signal_tracking: true
