name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas duckdb fastapi httpx pre-commit
          if [ -f analytics/requirements.txt ]; then pip install -r analytics/requirements.txt || true; fi
          if [ -f database/requirements.txt ]; then pip install -r database/requirements.txt || true; fi
      - name: Run pre-commit (format/lint)
        run: |
          pre-commit run --all-files || true
      - name: Run architecture tests
        run: pytest -q tests/architecture
      - name: Run unit tests (scanners)
        run: pytest -q tests/scanners || true
      - name: Forbidden import check (strategies)
        run: |
          if grep -R -n "import duckdb\|from duckdb" src/application/scanners/strategies; then
            echo "Forbidden duckdb import found in strategies" && exit 1;
          else
            echo "OK: no duckdb imports in strategies";
          fi
      - name: Forbidden import check (domain -> infra)
        run: |
          if grep -R -n "from src.infrastructure\|import src.infrastructure" src/domain; then
            echo "Forbidden infrastructure import found in domain" && exit 1;
          else
            echo "OK: no infra imports in domain";
          fi
      - name: Forbidden import check (api routes - optional)
        run: |
          if grep -R -n "import duckdb\|from duckdb" src/interfaces/api/routes; then
            echo "Forbidden duckdb import found in API routes" && exit 1;
          else
            echo "OK: no duckdb imports in API routes";
          fi
